# Merge, Join and Concatenate DataFrame

![merge_join_concatenate.jpg](data/merge_join_concatenate.jpg)

## Importing Libraries

In [1]:
import pandas as pd

## Loading Data

In [2]:
df1 = pd.read_csv('./data/lotr_1.csv')
df1

   FellowshipID FirstName     Skills
0          1001     Frodo     Hiding
1          1002   Samwise  Gardening
2          1003   Gandalf     Spells
3          1004    Pippin  Fireworks

In [3]:
df2 = pd.read_csv('./data/lotr_2.csv')
df2

   FellowshipID FirstName   Age
0          1001     Frodo    50
1          1002   Samwise    39
2          1006   Legolas  2931
3          1007    Elrond  6520
4          1008  Barromir    51